<template>
    <div>
      <div class="flex mt-5 justify-around" id="video-container">
        <div v-if="selected_videos.length != 0" class="grid grid-cols-3 space-x-2 p-5" ref="imageContainer">
          
          <div v-for="(video, index) in selected_videos" :key="index" class="relative">
            <div class="flex flex-col mb-3" id="content-area" @click="goToStudy">
              <img :src="video.video_thumbnail" alt="video-image" class="object-fit rounded-md video-img-item img-container">
              <span class="badge absolute top-1 left-1">
                <div id="badge" class="bg-white border-theme-red border-4 rounded-md font-bold text-theme-red text-lg p-0.5 pl-1 pr-1">
                  Lv. 3
                </div>
              </span>
              <div class="text-xl font-bold mt-2" id="video-name">
                {{video.video_name}}
              </div>
            </div>
          </div>
        </div>
        <div v-else>
          <div class="font-bold text-lg" id="no-content-area">해당 카테고리의 뉴스가 없습니다.</div>
        </div>
      </div>
    </div>
  </template>
  
  <script setup>
  import { ref, watch, onMounted, nextTick, defineProps } from 'vue';
  import { useRoute, useRouter } from "vue-router";

  const route = useRoute();
  const router = useRouter();

  const startIndex = ref(0);
  const endIndex = ref(3);

  const currentIndex = ref(0);
  const imageContainer = ref(null); // ref를 사용하여 DOM 요소에 접근할 변수 선언
  
  const goToStudy = () => {
    router.push("/study");
  };

  const props = defineProps({
    category: Number
  });

  const videoList = [
    {
      "_id": {
        "$oid": "65f71a71887cecf903ef326a"
      },
      "video_id": "u1KGbwrRrfk",
      "full_script": "  GOING ALONG WITH HIS 2020  ELECTION LIES. KEMP DOES HAVE A BIG NAME  STUMPING FOR HIM, FORMER VICE  PRESIDENT MIKE PENCE. LET'S GET TO CNN'S POLITICAL  DIRECTOR, DAVID CHALIAN. TELL US WHAT TO WATCH FOR  TOMORROW IN GEORGIA.  >> ALISON, YOU WERE BRIGHT. GOVERNOR BRIAN KEMP, THE \n       INCUMBENT GOVERNOR, TARGETED BY  DONALD TRUMP, BECAUSE BRIAN KEMP RIGHTLY AND CORRECTLY CERTIFIED  THE LEGITIMATE ELECTION OF JOE  BIDEN IN THE BATTLEGROUND STATE  THAT HELPED PROPEL HIM TO THE  PRESIDENCY. DONALD TRUMP HAS BEEN TELLING  HIS LIE ABOUT THE 2020 ELECTION  EVER SINCE AND THAT MAKES KEMP  TARGET NUMBER ONE. DONALD TRUMP MAY BE IN FOR A BIG LOSS HERE TOMORROW IF THE  PRE-ELECTION POLLS ARE CORRECT. YOU MENTIONED THE TRUMP VERSUS  PENCE FACTOR. TONIGHT PENCE HAS THAT RALLY FOR KEMP, TRUMP IS HOLDING A         TELL-RALLY FOR PERDUE. AS YOU KNOW, THEY ARE ON OTHER  SIDES OF THIS. THEY'RE TRYING TO CARVE OUT  THEIR OWN POLITICAL TURF INSIDE  THE REPUBLICAN PRIMARY IN  ADVANCE OF 2024. LOOK AT THIS STATEMENT FROM  DONALD TRUMP SPOKESPERSON TODAY  TO \"THE NEW YORK TIMES\" ABOUT  MIKE PENCE. NOW, DESPERATE TO CHASE HIS LOST RELEVANCE, PENCE IS PARACHUTING  TO RACES HOPING SOMEONE IS  PAYING ATTENTION. THAT'S PRETTY DIRECT AND SNIDE.  SO NO LOVE LOST DESPITE PENCE'S  LOYALTY TO DONALD TRUMP. THE OTHER THING WE'RE WATCHING  ARE EARLY VOTING TURNOUT  RECORDS. TAKE A LOOK ON THE REPUBLICAN  SIDE, PRE-ELECTION PRIMARY VOTES CAST THUS FAR, IN 2018 IT WAS  172,587. IN 2022, 406,388 REPUBLICAN  PRE-ELECTION PRIMARY VOTES. RECORD SETTING. AND, BY THE WAY, DEMOCRATS ARE  COMING OUT TO VOTE EVEN THOUGH  THEY DON'T HAVE A VERY  COMPETITIVE CONTEST AT THE TOP  OF THEIR TICKETS FOR GOVERNOR OR SENATE RACE. IN 2018 WHERE THERE WAS A  COMPETITIVE DEMOCRATIC PRIMARY,  151,204 PRE-ELECTION VOTES CAST, IN 2022, IT'S NEARLY 300,000,  NEARLY DOUBLE WHAT IT WAS FOUR  YEARS AGO IN THE PRIMARY SEASON, ALISON.  >> DAVID, REALLY INTERESTING  STUFF. LOOK AT THAT LEVEL OF  ENGAGEMENT. LOOKING AT THE NUMBERS IS  FASCINATING. AND YOU'RE FOLLOWING A  DEMOCRATIC RACE FOR SONG IN  TEXAS AND HOW ABORTION IS  PLAYING INTO IT. >> YEAH, THIS IS A FASCINATING  RACE. IT'S A RUNOFF BETWEEN THE  INCUMBENT MODERATE ESTABLISHMENT DEMOCRAT, ONE OF THE VERY FEW  DEMOCRATS THAT STILL PORTRAYS  HIMSELF AS A PRO-LIFE DEMOCRAT  IN THE CONGRESS. HE DOES HAVE SPEAKER PELOSI'S  BACKING AS THE INCUMBENT. BUT THE MORE PROGRESSIVE                                CHALLENGER RUNNING WITH BERNIE  SANDERS AND ELIZABETH WARREN. WE'LL SEE IF THE PRO-ABORTION  CANDIDATE CAN FIRE UP ENOUGH  PROGRESSES TO OVERCOME THE IN  DUMB BENT IN THIS RACE AND WHAT  THAT MAY MEAN FOR DEMOCRATS  TRYING TO HOLD ONTO THE DISTRICT IN THE FALL, ALISON.  >> DAVID CHALIAN, WE'LL BE  WATCHING, AS WE KNOW YOU WILL  BE. THANK YOU. >> THANKS.  >>> SO LET'S DISCUSS FURTHER  WITH CNN POLITICAL COMMENTATOR  SCOTT JENNINGS, WHO SERVED AS  SPECIAL ASSISTANT TO PRESIDENT  GEORGE W. BUSH. GREAT TO SEE YOU. LET'S TALK ABOUT WHAT'S GOING ON IN GEORGIA WITH BRIAN KEMP. SO HE HAD TO TODAY TRY TO  EXPLAIN HIS RELATIONSHIP WITH  DONALD TRUMP, AND HERE IS WHAT  HE SAID. >> I HAD A GREAT RELATIONSHIP  WITH MIKE PENCE, I HAD A GREAT  RELATIONSHIP WITH PRESIDENT  TRUMP. I'VE NEVER SAID ANYTHING BAD  ABOUT HIM, I DON'T PLAN ON DOING THAT. I'M NOT MAD AT HIM. I THINK HE'S JUST MAD AT ME AND  THAT'S SOMETHING THAT I CAN'T  CONTROL. >> OKAY, SO NUMBER ONE, WHAT DO  YOU HEAR IN THAT STATEMENT? AND, NUMBER TWO, IF KEMP WINS  BIGLY, AS PRESIDENT TRUMP USED  TO LIKE TO SAY, DOES THAT CHANGE DONALD TRUMP'S KINGMAKER STATUS? >> WELL, FIRST OF ALL, FOR BRIAN KEMP I THINK THE KIND OF  AUTHENTICITY YOU HEARD IN THAT  ANSWER IS THE WAY HE'S RUN HIS  CAMPAIGN, AND IT'S IN LARGE PART WHY HE'S WINNING SO BIG HERE. HE DIDN'T TRY TO CONTORT  HIMSELF, HE DIDN'T TRY TO PLAY  SEMANTICS GAMES ABOUT HOW THIS  HAS GONE DOWN. HE JUST ACCEPTED THE REALITY,  LEANED INTO IT, STATED HIS  POSITION. AND I THINK THE VOTERS HAVE  REWARDED HIM FOR IT. GOVERNORS RACES ARE OFTEN ABOUT  COMPETENCE, LIKABILITY,  AUTHENTICITY AND THE FUTURE AND  KEMP HAS JUST REALLY DONE GREAT  IN EVERY SINGLE CATEGORY. REGARDING THE FUTURE OF THE  REPUBLICAN PARTY, I THINK THAT  WAS THE SECOND PART OF YOUR  QUESTION --  >> WELL, THE KINGMAKER STATUS,  DO YOU THINK HIS KINGMAKER  STATUS, DONALD TRUMP'S, HINGES  ON THIS? >> WELL, I MEAN, LOOK, I THINK  HE'S STILL EXTREMELY INFLUENTIAL WITH REPUBLICAN VOTERS. IT'S JUST IN THIS PARTICULAR  CASE HE RAN UP AGAINST SOMEBODY  WHO FIGURED OUT HOW TO SOLVE THE EQUATION. IT DOESN'T MEAN DONALD TRUMP  ISN'T AN INFLUENTIAL PERSON  ANYMORE. KEMP HAS HAD THE BENEFIT, TOO -- AND SOMETIMES IN THE REPUBLICAN  PARTY THE WAY YOU CAN EXPLAIN  SUCCESS IS BY HAVING ALL THE  RIGHT ENEMIES. DeSANTIS HAS THIS RIGHT NOW. KEMP HAS HAD ALL THE RIGHT  ENEMIES. HE DEFEATED STACEY ABRAMS, STOOD UP AGAINST SOME OF THE  CORPORATIONS IN GEORGIA IN 2020, HE STUCK TO HIS GUNS ON THE  GEORGIA ELECTION LAW THAT A LOT  OF THE NATIONAL LIBERAL  ESTABLISHMENT CAME DOWN ON HIM  FOR. SO EVEN THOUGH DONALD TRUMP WAS  MAD AT HIM, HE THEN CULTIVATED  SOME OF THE RIGHT ENEMIES THAT I THINK SIGNALLED TO REPUBLICAN  VOTERS, BRIAN KEMP REALLY IS ONE OF US, DESPITE DONALD TRUMP'S  OPINION. SO DOES IT TOTALLY THROW OUT HIS KINGMAKER STATUS? NO. DOES IT SHOW A WAY TO STAND UP  TO DONALD TRUMP, YES. AND DOES IT SHOW THE RIGHT WAY  TO RUN A CAMPAIGN WHEN YOU HAVE  THIS DYNAMIC, ABSOLUTELY. PEOPLE SHOULD STUDY THE BRIAN  KEMP MODEL.  >> IT'S INTERESTING TO HEAR WHAT SOME REPUBLICAN GOVERNORS ARE  SAYING ABOUT DONALD TRUMP AND  HOW HE'S CONDUCTING HIMSELF IN  2022. BASICALLY THEY'RE CALLING HIS  INVOLVEMENT HIS PERSONAL  VENDETTA TOUR AND ONE OF THE  PEOPLE TALKING ABOUT IT IS  FORMER NEW JERSEY GOVERNOR,  CHRIS CHRISTIE. HE SAID THIS YESTERDAY, THIS IS  JUST NOT THE BEST USE --  BASICALLY WHAT HE'S TALKING  ABOUT IS HAVING TO SPEND MONEY  IN GEORGIA TO FEND OFF DONALD  TRUMP'S ATTACKS. AND HE SAYS THIS IS JUST NOT THE BEST USE OF OUR MONEY. WE WOULD MUCH RATHER USE IT IN  RACES AGAINST DEMOCRATS, BUT IT  WAS MADE NECESSARY BECAUSE  DONALD TRUMP DECIDED ON THE  VENDETTA TOUR THIS YEAR AND SO  WE NEED TO MAKE SURE WE PROTECT  THESE FOLKS WHO ARE THE OBJECTS  OF HIS VENGEANCE. SO WHAT IS THE LARGER POINT  HERE? >> WELL, THE LARGER POINT IS  CHRIS CHRISTIE IS EXUDING THE  QUAINT NOTION THAT POLITICAL  PARTIES ARE ABOUT THE TEAM AND  THE HEALTH AND FUTURE OF THE  PARTY AS A WHOLE. HE'S DOING THAT IN THE ERA OF  DONALD TRUMP WHO HAS MADE THE  REPUBLICAN PARTY ALL ABOUT  HIMSELF. HE DOESN'T THINK ABOUT IT WOULD  BE BETTER SPENT HERE OR THERE,  HE DOESN'T VIEW THE WORLD  THROUGH THAT LENS. FORTUNATELY, THE REPUBLICAN  GOVERNORS ASSOCIATION DECIDED TO VIEW THE WORLD EXACTLY THROUGH  THAT LENS AND THAT'S THE ROLE OF A PARTY OR PARTY COMMITTEE, TO  HELP THE INCUMBENTS AND ROCK  STAR OFFICE HOLDERS WIN  ELECTION. IN GEORGIA THAT'S A BIG DEAL  BECAUSE STACEY ABRAMS IS ONE OF  THE TOP DEMOCRAT RECRUITS IN THE COUNTRY. SHE WILL NOT LACK FOR RESOURCES. SO EVERY DOLLAR WE'VE THROWN  AWAY IN THE USELESS REPUBLICAN  PRIMARY WE COULD HAVE SPENT IN  THE FALL. THAT'S A GOOD WAY TO LOOK  STRATEGIC WAY TO LOOK AT IT. I'M GLAD HE'S STANDING UP FOR  THAT POINT OF VIEW BECAUSE IT  STRENGTHENS THE PARTY AND IT  WORKS.  >> I'M NOT SURE THAT CONGRESSMAN MO BROOKS IS FOLLOWING YOUR  CREED. HE'S RUNNING FOR SENATE IN  ALABAMA AND HE IS DOING SO BY  GOING AFTER YOUR LONG-TIME BOSS  AND COLLEAGUE, MITCH MCCONNELL. SO LET ME READ TO YOU WHAT HE  SAYS. MO BROOKS SAYS ON TWITTER, WE  ONLY HAVE A COUPLE MORE DAYS  UNTIL THE PRIMARY ELECTION. REMEMBER THIS ELECTION IS A  BATTLE BETWEEN MITCH MCCONNELL  AND THE SWAMP VERSUS GRASSROOTS  CONSERVATIVES. IS THAT A WINNING STRATEGY? >> WELL, I MEAN, MO BROOKS'  PROBLEM IS THAT DONALD TRUMP WAS FOR HIM AND NOW HE'S AGAINST HIM AND BAILED OUT ON HIM AND HE'S  TRYING TO MAKE THIS RACE ABOUT  SOMETHING ELSE. I DON'T THINK IT'S GOING TO BE A WINNING STRATEGY. THAT RACE HAS GOTTEN  INTERESTING, THOUGH. BROOKS HAD FALLEN BACK AND NOW  THE LATEST POLLING SHOWS HIM  RISING. IT SEEMS LIKE WE'RE HEADING FOR  A RUNOFF IN ALABAMA. ALABAMA SENATE IS ONE OF THE  MOST INTERESTING, ONE OF THE  CLOSEST RACES. IT'S GOT SOME OF THE STRANGEST  DYNAMICS AND REALLY I THINK ONE  OF THE BEST CANDIDATES IN THE  COUNTRY, KAT",
      "senteceList": [
        {
          "start": 1.401,
          "text": " going along with his 2020 election lies."
        },
        {
          "start": 4.437,
          "text": "Kemp does have a big name stumping for him, former vice president mike pence."
        },
        {
          "start": 8.441,
          "text": "Let's get to cnn's political director, david chalian."
        },
        {
          "start": 12.912,
          "text": "Tell us what to watch for tomorrow in georgia."
        },
        {
          "start": 15.315,
          "text": "Alison, you were bright."
        },
      ],
      "category_name": "Politics",
      "video_date": "2022-05-23",
      "video_name": "What to watch for in the Georgia and Texas primaries",
      "video_thumbnail": "https://i.ytimg.com/vi/u1KGbwrRrfk/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\\u0026rs=AOn4CLCXJ3o1umHI4ZK7aTjFBkYDKKCPmA"
    },
    {
      "_id": {
        "$oid": "65f71a71887cecf903ef326b"
      },
      "video_id": "CE8R1684oGs",
      "full_script": ". WE ARE FOLLOWING THIS CASE. LET'S JUST FIRST TALK ABOUT  WHAT'S NEW TODAY. >> Reporter: A LOT. FIRST OF ALL, YOU KNOW, THERE'S  A BIG ISSUE IN THE TRIAL, WHAT  CAUSED JOHNNY DEPP'S FINGERTIP  TO BE SEVERED. COMPLETELY CUT OFF.              HE TESTIFIED WHEN THEY WERE IN  AUSTRALIA, THEY WERE AT THE HOME THEY WERE STAYING AT. HE WAS SITTING AT THE BAR AND  AMBER HEARD THREW TWO VODKA  BOTTLES AT HIM. ONE BASHED AND CRACKED RIGHT ON  THE EDGE OF THE BAR AND IN SO  DOING, IT SEVERED HIS FINGERTIP. WELL, TODAY HEARD'S TEAM PUT ON  AN ORTHOPEDIC SURGEON WHO  SPECIALIZES IN LOWER  EXTREMITIES. HE LOOKED AT THE X-RAIES. HE SAID I DON'T THINK SO. LISTEN TO THIS. >> IT'S NOT CONSISTENT WITH WHAT WE SEE IN THE DESCRIBED INJURY  PATTERN OR IN THE CLINICAL  PHOTOGRAPHS. AND THERE ARE SEVERAL ELEMENTS. THERE'S THE DESCRIPTION WAS A  HAND BEING FLAT ON A BAR AND THE BOTTLE CRUSHING THE FINGER FROM  THE TOP. BUT LOOKING AT THE IMAGES,  THERE'S REALLY NO SIGNIFICANT  INJURY TO THE DORSAL OF THE  FINGER, AND TO CREATE THE TYPE  OF INJURY WITH THAT TYPE OF A  CRUSH INJURY, WE WOULD  ANTICIPATE BOTH INJURY TO THE  FINGERNAIL AND OTHER PARTS OF  THE FINGER. >> SO ON CROSS EXAMINATION, THE  DEFENSE WENT THROUGH PICTURES OF THE SCENE THAT THE BUTLER HAD  TAKEN. THIS IS IMPORTANT FORENSIC  EVIDENCE RIGHT HERE. AND THE WITNESS SAID THAT HE HAD NOT SEEN THOSE PICTURES. AND IT SHOWS BROKEN GLASS,  BROKEN VODKA BOTTLES, EVEN THE  FINGERTIP OF DEPP IS UNDERNEATH  THE BAR, ACTUALLY WRAPPED AROUND SOME PAPER TOWEL. NOW, AMBER HEARD TESTIFIED THAT  SHE DOESN'T KNOW HOW THE TIP OF  THE FINGER WAS SEVERED OFF, BUT  SHE SAW DEPP TAKE A PHONE IN HIS RAGE OUT OF THE WALL THAT WAS IN THE WALL AT THE BAR AREA. BUT THERE ARE NO PICTURES OF  THAT PHONE. THE JURY HAS NOT SEEN PICTURES  OF A PHONE THAT WAS JUST TAKEN  OUT OF THE WALL OR THE DRY WALL  THAT HAD THE PHONE IN PLACE ON  THE WALL. AND SO WHY DO WE CARE ABOUT  THIS? IT'S ALL ABOUT CREDIBILITY. BECAUSE THIS IS A DEFAMATION  CASE, AND IF YOU'RE DEFAMED,  THEN THE PERSON THAT DEFAMED YOU IS NOT TELLING THE TRUTH",
      "senteceList": [
        {
          "start": 1.267,
          "text": "."
        },
        {
          "start": 1.434,
          "text": "We are following this case."
        },
      ],
      "category_name": "Politics",
      "video_date": "2022-05-23",
      "video_name": "Expert witness disputes cause of Johnny Depp's severed finger",
      "video_thumbnail": "https://i.ytimg.com/vi/CE8R1684oGs/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\\u0026rs=AOn4CLBjjS02PE79n66PMSHTiUIHblpsDA"
    },
    {
      "_id": {
        "$oid": "65f71a71887cecf903ef3274"
      },
      "video_id": "0NBxIkXTSUo",
      "full_script": "  SO --  >> THANKFULLY THOSE DREAMS NEVER BECAME REALITY.  >> IN THE MORNING THEY PICKED ME UP FROM THE PRISON IN AN FSB  CONVOY, PUT ME ON THE PLANE. DID YOU KNOW WHERE YOU WERE  GOING? >> I ASKED THE FSB LIKE SECURITY TEAM THERE, ARE WE GOING TO  TURKEY, AND THEY WERE LIKE, YOU  KNOW, YEAH. I THOUGHT THAT LIKE MAYBE THE  U.S. EMBASSY IN TURKEY WAS GOING TO COME PICK ME UP. I HAD NO IDEA WHAT WAS GOING ON, AND THESE VANS WERE DRIVING BACK AND FORTH TO THE JET ON THE  RUNWAY AND MAYBE THAT'S THE U.S. EMBASSY AND THE FSB WAS LIKE NO, THAT'S OKAY. MAYBE THAT'S LIKE THE EMBASSY. AND SHE SAID HOW DO I KNOW THAT  THAT'S NOT THEM, AND THEY SAID  WE HAVE A MAN THERE IN AMERICA,  AMERICAN JET WILL FLY HERE. HE WILL LAND NEXT TO US. WE WILL LEAVE THE PLANE, HE WILL LEAVE THE PLANE. YOU WILL CROSS EACH OTHER ON THE RUNWAY AND GET IN YOUR OWN PLANE AND WHEN I TOLD HIM THAT I WAS  LIKE NO, THIS GUY HAS TO BE  SCREWING WITH ME, AND I WAS LIKE REALLY, AND HE SAID YES. HE SAID IT'S PRETTY COOL, HUH? HE SAID DO YOU FEEL COOL, AND I  SAID ARE, I DON'T KNOW. HE SAID YOU SHOULD BECAUSE THIS  PLANE COSTS A BOTH LOAD OF  MONEY. HE SAID THEY WOULD NEVER FLY US  ON THIS PLANE.  >> AT THIS POINT WERE YOU  ALLOWING YOURSELF TO FEEL HOPE? >> I WAS STILL AVOIDING THAT,  AND IT WAS DIFFICULT. >> AN AMERICAN FINALLY DID SHOW  UP. IT WAS THE TOP DIPLOMAT WITH THE SPECIAL PRESIDENTIAL ENVOY FOR  HOSTAGE AFFAIRS. >> SO COLONEL KARSTENS CAME ON,  ROGER KARSTEN FROM SPEHA, AND I  WAS LIKE, MAN WORKS IS THIS  ACTOR THEY SENT ME? LIKE ARNOLD SCHWARZENEGGER  COMING ON HERE TO WASTE ALL THE  FSB GUYS AND JUST RESCUE ME, SO  HE CAME AND GOT ON THE JET. HE SAYS I'M ROGER CARSTENS, I  HAVE TO IDENTIFY YOU, AND I  SAID, YEAH, YOU KNOW, IT'S ME. I'M TREVOR. HE DIDN'T RESPOND TO THAT, AND  THEN HE LEFT, AND I WAS KIND OF  LIKE -- LIKE WHAT? DUDE, SO I WAS LIKE CAN I GO,  AND THE FSB SAID NO, AND I SAID  WHAT'S THE PROBLEM? ONE OF THEM LOOKSP-AT-AT ME AND  HE SAYS ARE YOU SURE AMERICA  WANTS YOU BACK? THEY SENT THEIR GUY OVER TO THE  OTHER JET. THEY CHECK OUT THEIR GUY. AND WE -- WE DID THE EXCHANGE,  WALKED PAST KONSTANTIN  YARASHEYKO.  >> A RUSSIAN PILOT IN A 20-YEAR  SENTENCE FOR CONSPIRING TO BRING $100 MILLION WORTH OF COCAINE  INTO THE UNITED STATES.  >> AND HOW DID HE LOOK VERSUS  HOW DID YOU LOOK? >> YEAH. SO HE'S NOT BEEN ON ANY HUNGER  STRIKES THERE, NOT MISSING ANY  MEALS. >> ONCE ON BOARD THE PLANE,  TREVOR GOT A REAL MEAL. >> THEY GAVE ME A STEAK ON  THERE, AND THAT WAS THE BEST  THING I'VE EVER ATE IN MY WHOLE  LIFE. I'LL NEVER FORGET THAT.  >> AND THERE WAS ALSO THE FIRST  PHONE CALL HOME TO MOM AND DAD.  >> THAT MOMENT WAS EXTREMELY  SURREAL. I DON'T EVEN REALLY REMEMBER  WHAT I SAID THERE. I THINK I TOLD THEM, YOU KNO",
      "senteceList": [
        {
          "start": 0.667,
          "text": " so -- thankfully those dreams never became reality."
        },
        {
          "start": 12.445,
          "text": "In the morning they picked me up from the prison in an fsb convoy, put me on the plane."
        },
        {
          "start": 20.186,
          "text": "Did you know where you were going?"
        },
      ],
      "category_name": "Sports",
      "video_date": "2022-05-22",
      "video_name": "Trevor Reed describes his release from Russian prison",
      "video_thumbnail": "https://i.ytimg.com/vi/0NBxIkXTSUo/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\\u0026rs=AOn4CLBtNCwmbcgHwIYOcNlka1RePcpwyw"
    },
    {
      "_id": {
        "$oid": "65f71a71887cecf903ef3275"
      },
      "video_id": "Mbwls1iJLWw",
      "full_script": "  UKRAINE WITH THE STORY. SUZANNE? >> Reporter: GOOD EVENING, PAM. EXCLUSIVE TO CNN, A RUSSIAN  JUNIOR OFFICER WHO SPEAKS THAT  HE IS ANONYMOUS TO PROTECT THE  SAFETY AND THE IDENTITY SPEAKING TO CNN SAYING HE WAS A PART OF  THE UNIT FEBRUARY 22nd THE TROOP BUILD-UP ALONG THE BORDER WITH  UKRAINE AND THAT EVENING THAT  THEY WERE ORDER DS TO GIVE OVER  THE CELL PHONES AND LOST  COMMUNICATION WITH THE WORLD AND ORDERED TO PAINT THE \"Zs\" ON THE VEHICLES TO SYMBOLIZE THE  INVASION AND NO IDEA THAT THAT  WAS IN FACT THE MISSION. THE FOLLOWING DAY IN CRIMEA. HE DIDN'T KNOW THEY WERE GOING  TO MOVE FORWARD BUT ON FEBRUARY  24th HE SAYS, YES, HE WAS PART  OF THE LAUNCH OF THE WAR INSIDE  UKRAINE AND SAID MANY COMRADES  AND HIMSELF DID NOT UNDERSTAND  THE GOAL. HE TELLS CNN, QUOTING HERE, WE  WERE NOT HAMMERED WITH A  UKRAINIAN NAZI RHETORIC. MANY DID NOT UNDERSTAND WHAT  THIS WAS ALL FOR AND WHAT WE  WERE DOING HERE AND THE OFFICER  DESCRIBING THE DRIVE AND  ACTUALLY CONFRONTING LOCALS  SAYING HERE QUOTING, IN  GENESEEING THE LOCALS WE TENSED  UP. SOME HID WEAPONS UBDS NOOERT THE CLOTHES AND THEY FIRED. HE TOLD CNN HE WOULD HIDE HIS  FACE FROM THE UKRAINIANS  EMBARRASSED OUT OF SHAME AND  SAFETY AND DIDN'T WANT THEM TO  SEE HIM ON THEIR LAND AND SAID  THE SECOND OR THIRD DAY WHEN  RUSSIAN FORCES CAME IRND FIRE  ATTACK AND AND HE WAS IN A STATE OF AFTERSHOCK AND A COUPLE WEEKS INTO THE WAR THINGS CHANGED FOR  HIM SAYING HE GOT A RADIO  RECEIVER AND GOT A LOOK INTO THE NEWS HERE SAYING THAT'S HOW I  LEARNED THAT SHOPS ARE CLOSING  IN RUSSIA AND THE ECONOMY IS  COLLAPSING. I FELT GUILTY AND MORE GUILTY  BECAUSE WE CAME TO UKRAINE. AND THEN HE CONCLUDES, PAM, IN  THE END I GATHERED THE STRENGTH, WENT TO WRITE A LETTER OF  RESIGNATION. HE SAID THERE COULD BE A  CRIMINAL CASE. THAT REJECTION IS BETRAYAL. I STOOD MY GROUND. PAM, HE WENT OFF. HE IS NOW BA",
      "senteceList": [
        {
          "start": 2.068,
          "text": " ukraine with the story."
        },
        {
          "start": 5.605,
          "text": "Suzanne?"
        },
        {
          "start": 5.939,
          "text": "Reporter: good evening, pam."
        },
        {
          "start": 8.408,
          "text": "Exclusive to cnn, a russian junior officer who speaks that he is anonymous to protect the safety and the identity speaking to cnn saying he was a part of the unit february 22nd the troop build-up along the border with ukraine and that evening that they were order ds to give over the cell phones and lost communication with the world and ordered to paint the \"zs\" on the vehicles to symbolize the invasion and no idea that that was in fact the mission."
        },
      ],
      "category_name": "Health",
      "video_date": "2022-05-22",
      "video_name": "Russian officer reveals why he quit Putin's war",
      "video_thumbnail": "https://i.ytimg.com/vi/Mbwls1iJLWw/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\\u0026rs=AOn4CLDHWKf_SdnMPb0HASxTKJ0NrVQnOg"
    },
    {
      "_id": {
        "$oid": "65f71a71887cecf903ef3276"
      },
      "video_id": "lwjjBDUoHWw",
      "full_script": "  WITH OTHER AMERICANS JAILED  ABROAD. HARRISON LEE'S SON IS BEING  JAILED. THANK YOU FOR JOINING. YOU HAVE A RELATIVE, YOUR  FATHER, DETAINED OVERSEAS IN  SHANGHAI ON STATE SECURITY  CHARGES. WHY DO YOU SAY THAT THOSE  CHARGES ARE POLITICALLY  MOTIVATED? >> SURE. SO MANY FATHER IS AN ORDINARY  AMERICAN. HE CAME TO THE QUITE IN 1989  WITH $200 IN HIS POCKET. HE STARTED TO WORK IN FOOD  SERVICE AND AN ORDINARY  AMERICAN. HE RAN A ONE-MAN BUSINESS OWNER. HE'S NOT A MULTIMILLIONAIRE. AN ORDINARY PERSON. YOU CAN IMAGINE THE SHOCK WHEN  SUDDENLY IN SEPTEMBER OF 2016 HE WAS TAKEN FROM US AND THE  CHARGING OF ESPIONAGE LEVIED  AGAINST HIM ARE 100% POLITICALLY MOTIVATED. THESE ARE THE EXACT SAME CHARGES USED TO DETAIN OTHERS. THE STATE SECRETS THAT MY FATHER IS ALLEGED TO HAVE STOLEN IS  INFORMATION THAT CAN BE FREELY  FOUND ON THE INTERNET. THAT ILLUSTRATES THAT IN INDEED  THE CHARGES ARE THE FALSE. THE U.N. WORKING GROUP RULED IT  TO BE ARBITRARY AND THE U.S.  GOVERNMENT IS TAKING UP THE  CASE. AND WHILE I'M GRATEFUL IT HAS  NOT BEEN ENOUGH. I HAVEN'T SEEN MY FATHER IN SIX  YEARS NOW. I DON'T KNOW HOW MUCH LONGER IT  WILL BE. THIS ADMINISTRATION IS  WORKINGING HARD BUT NOT HARD  ENOUGH AND NEED TO GET TOGETHER, PUTT TOGETHER AN INTERAGENCY  EFFORT AND ITERATE SOLUTIONS  BECAUSE I DON'T THINK THERE'S A  REAL PLAN TO GET HIM OUT. IT IS SIX YEARS. I DON'T KNOW THE HOLDUP. I WANT MY DAD HOME.  >> TELL US MORE ABOUT THE  COMMUNICATIONS YOU HAVE HAD WITH THE U.S. GOVERNMENT.  >> CERTAINLY IT IS VARIED. I'M GRATEFUL TO BE IN TOUCH WITH THEM ON A WEEKLY BASIS AND TAKES A VILLAGE TO RESOLVE THE CASES. THAT'S THE REALITY OF THE  SITUATION. I GET THE SENSE THAT THERE'S  DIFFERENT GOVERNMENT AGENCIES TO WORK TOGETHER TO GET THIS DONE  AND SEEMS LIKE THE PROCESS TAKEN MONTHS AND MONTHS AT EACH STEP  AND NOT ACCEPTABLE. WHILE THIS IS HAPPENING YOU HAVE INNOCENT AMERICANS BEING  TORTURED, WRONGFULLY HELD  WITHOUT COMMUNICATION. MY FATHER'S ONLY MEANS OF  TALKING TO THE WORLD ARE THE  SEVEN-MINUTE CALLS AND MAKES IT  CLEAR HE CAN'T TELL US THE FULL  EXTENT OF WHAT HAS HAPPENED IN  PRISON. HE IS DIAGNOSED WITH HIGH BLOOD  PRESSURE AND HAS HAD A STROKE. HE IS CRAMMED INTO A CELL AND  SHANGHAI IS HOT AND HUMID AND NO CLIMATE CONTROL IN THE CELL. THEY NEED TO PLACE A GREATER  PRIOR TE AND NUMBER ONE THING TO DO IS TO MEET WITH THE FAMILIES  THAT HE DID WITH AN OTHER  FAMILIES AND INCLUDING THE  WRONGFULLY DETAINED AMERICANS IN CHINA. WE ARE WAITING TO MEET WITH THE  PRESIDENT BUT HAD NO LUCK TO  DOING SO.  >> WHAT DO YOU THINK THE U.S.  GOVERNMENT SHOULD DO? SHOULD THEY BE PAYING RANSOMS? A PRISONER EXCHANGE? IF YOUR DAD COULD WATCH THIS NOW WHAT WOULD YOU SAY TO HIM? >> CHINA I'M ALWAYS TOLD IS A  COMPLEX COUNTRY WITH THESE KINDS OF CASES AND THE SOLUTIONS THAT  HAVE WORKED IN THE PAST THAT  THEY VARY AND I THINK THERE'S  NOT A CONSISTENT STRATEGY SO I  LEAVE IT IN THE HANDS OF THE  GOVERNMENT EXPERTS BUT RIGHT NOW THEY NEED TO TAKE AN ACTION AND  THAT'S WHERE WE'RE AT WITH MY  FATHER. TO HELP WITH THAT SENIOR  ADMINISTRATION OFFICIALS LIKE  PRESIDENT BIDEN AND NATIONAL  SECURITY ADVISER SULLIVAN THAT  PROMISED A CALL MORE THAN FIVE  MONTHS AGO THAT HASN'T TALKED TO THE FAMILIES WE WANT TO TALK TO  HIM TO PRESENT THE SIDE OF THE  STORY TO HELP COME UP WITH A  PLAN. WE WANT TO HELP THEM COME UP  WITH A PLAN.  >> WHAT IS YOUR MESSAGE TO YOUR  DAD? >> DAD, I AM JUST SO IMPRESSED  BY HOW STRONG AND RESILIENT YOU  HAVE BEEN THROUGH SIX YEARS OF  CHINESE PRISON. I DON'T WANT TO KNOW WHAT'S  HAPPENED TO YOU. I KNOW THAT YOU HAVE SUFFERED  IMMENSELY FOR A CRIME YOU DID  NOT COMMIT. I KNOW THAT THEY WANT TO WORK  HARD IN THE U.S. GOVERNMENT BUT  IT IS PRIORITIZATION. I WILL NOT GIVE UP UNTIL YOU ARE HOME IN NEW YORK BECAUSE TO DO  OTHERWISE WOULD NOT BE RIGHT. ",
      "senteceList": [
        {
          "start": 3.069,
          "text": " with other americans jailed abroad."
        },
        {
          "start": 12.012,
          "text": "Harrison lee's son is being jailed."
        },
        {
          "start": 15.315,
          "text": "Thank you for joining."
        },
      ],
      "category_name": "Business",
      "video_date": "2022-05-22",
      "video_name": "Son urges for help for father detained in China",
      "video_thumbnail": "https://i.ytimg.com/vi/lwjjBDUoHWw/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\\u0026rs=AOn4CLB_xpA4cFNN2ORNW0Otp5zm91ydzA"
    },
  ]

  // prop으로 전달받은 카테고리의 video 만 필터링
  const catMapping = {
    0: "Politics",
    1: "Health",
    2: "Business",
    3: "sports",
    4: "travel",
    5: "style",
  }

  const selected_videos = ref([]);

  onMounted(() => {
    updateVideoList(props.category)

  });

  watch(() => props.category, (newValue,) => {
      updateVideoList(newValue);
  });

  const updateVideoList = (category) => {
    selected_videos.value = [];

    for (const video of videoList) {
        if (video["category_name"] == catMapping[category]) {
            selected_videos.value.push(video);
        }
    }
  }


  </script>
  <style scoped>
  #video-container {
    border: 1px solid lightgray;
    border-radius: 10px;
    width: 80vw;
    
  }

  .img-container {
    overflow: hidden;
    height: 25vh;
    object-fit: cover;
  }

  #video-name {
    overflow: hidden;
    text-overflow: ellipsis;
    line-height: 1.4em;
    height: 2.8em;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
    width: 23vw;
  }

  #no-content-area, #content-area {
    height: 70vh;
    display: flex;
    align-items: center;

  }



  </style>
  